# Generated by Django 5.1.6 on 2025-02-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Something',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute1', models.DateField(null=True)),
                ('attribute2', models.DateField(null=True)),
                ('attribute3', models.CharField(max_length=32, null=True)),
                ('attribute4', models.CharField(max_length=16, null=True)),
                ('attribute5', models.BooleanField(null=True)),
            ],
        ),
    ]
