# Generated by Django 5.1.6 on 2025-02-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_historicalevents_delete_something'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalevents',
            name='is_peaceful',
            field=models.BooleanField(default=False),
        ),
    ]
