# Generated by Django 5.1.6 on 2025-02-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='historicalEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('title', models.CharField(max_length=32, null=True)),
                ('category', models.CharField(max_length=16, null=True)),
                ('is_peaceful', models.BooleanField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Something',
        ),
    ]
